name = "next-14-hello-world-app--next-on-pages"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]
main = "./.vercel/output/static/_worker.js/index.js"
assets = { directory = "./.vercel/output/static", binding = "ASSETS" }

no_bundle = true
base_dir = "./.vercel/output/static/_worker.js"

rules = [{ type = "ESModule", globs = ["**/*.js"], fallthrough = true }]
