main = ".open-next/worker.ts"
name = "next-14-hello-world-app--open-next"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }
